"""initial schema

Revision ID: 8fcb26067dd1
Revises: 
Create Date: 2026-09-05 04:06:42.330535

"""
from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '8fcb26067dd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """创建完整应用结构；vector 扩展必须先于向量列创建。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('agent_traces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('intent', sa.String(length=64), nullable=True),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('guardrail_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('handoff_required', sa.Boolean(), nullable=True),
    sa.Column('final_answer', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_traces_conversation_id'), 'agent_traces', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_agent_traces_trace_id'), 'agent_traces', ['trace_id'], unique=True)
    op.create_index(op.f('ix_agent_traces_user_id'), 'agent_traces', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('handoff_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_conversation_id'), 'conversations', ['conversation_id'], unique=True)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('evaluation_dataset',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=64), nullable=True),
    sa.Column('expected_answer', sa.Text(), nullable=True),
    sa.Column('expected_source', sa.String(length=255), nullable=True),
    sa.Column('should_call_tool', sa.String(length=8), nullable=True),
    sa.Column('should_transfer_human', sa.String(length=8), nullable=True),
    sa.Column('difficulty', sa.String(length=16), nullable=True),
    sa.Column('evaluation_notes', sa.Text(), nullable=True),
    sa.Column('expected_tool_name', sa.String(length=64), nullable=True),
    sa.Column('expected_route', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question', name='uq_evaluation_dataset_question')
    )
    op.create_index(op.f('ix_evaluation_dataset_category'), 'evaluation_dataset', ['category'], unique=False)
    op.create_table('intent_taxonomy',
    sa.Column('intent_id', sa.String(length=64), nullable=False),
    sa.Column('intent', sa.String(length=64), nullable=False),
    sa.Column('intent_cn', sa.String(length=64), nullable=True),
    sa.Column('example_question', sa.Text(), nullable=True),
    sa.Column('processing_method', sa.Text(), nullable=True),
    sa.Column('requires_tool', sa.String(length=8), nullable=True),
    sa.Column('tool_name', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('intent_id'),
    sa.UniqueConstraint('intent')
    )
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('chunking_strategy', sa.String(length=64), nullable=True),
    sa.Column('embedding_model', sa.String(length=64), nullable=True),
    sa.Column('access_level', sa.String(length=32), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_index(op.f('ix_knowledge_documents_category'), 'knowledge_documents', ['category'], unique=False)
    op.create_table('logistics_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('logistics_id', sa.String(length=64), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logistics_events_logistics_id'), 'logistics_events', ['logistics_id'], unique=False)
    op.create_table('products',
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('series', sa.String(length=128), nullable=True),
    sa.Column('release_date', sa.String(length=16), nullable=True),
    sa.Column('official_url', sa.String(length=512), nullable=True),
    sa.Column('source_date', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_table('promotions',
    sa.Column('promo_id', sa.String(length=64), nullable=False),
    sa.Column('promo_type', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_type', sa.String(length=64), nullable=True),
    sa.Column('discount_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('min_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('applicable_products', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.String(length=16), nullable=True),
    sa.Column('end_date', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('stackable', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('promo_id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sources',
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('page_title', sa.String(length=255), nullable=True),
    sa.Column('fetch_date', sa.String(length=16), nullable=True),
    sa.Column('is_official', sa.String(length=8), nullable=True),
    sa.Column('applicable_version', sa.String(length=64), nullable=True),
    sa.Column('source_priority', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('data_status', sa.String(length=64), nullable=True),
    sa.Column('conflict_note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_index(op.f('ix_sources_product_id'), 'sources', ['product_id'], unique=False)
    op.create_table('sync_manifests',
    sa.Column('sync_domain', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('sync_version', sa.String(length=32), nullable=False),
    sa.Column('statistics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('sync_domain')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=128), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_knowledge_chunks_document_position')
    )
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'knowledge_chunks', ['document_id'], unique=False)
    op.create_index('ix_knowledge_chunks_embedding_hnsw', 'knowledge_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('sender', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=32), nullable=False),
    sa.Column('intent', sa.String(length=64), nullable=True),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('orders',
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=True),
    sa.Column('variant_id', sa.String(length=64), nullable=True),
    sa.Column('product_name', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('coupon_discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=64), nullable=True),
    sa.Column('order_status', sa.String(length=32), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pay_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ship_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('receive_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_orders_order_status'), 'orders', ['order_status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('variant_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('ram', sa.String(length=64), nullable=True),
    sa.Column('storage', sa.String(length=32), nullable=True),
    sa.Column('color', sa.String(length=255), nullable=True),
    sa.Column('processor', sa.String(length=128), nullable=True),
    sa.Column('screen_size', sa.String(length=64), nullable=True),
    sa.Column('screen_type', sa.String(length=255), nullable=True),
    sa.Column('refresh_rate', sa.String(length=32), nullable=True),
    sa.Column('resolution', sa.String(length=64), nullable=True),
    sa.Column('rear_camera', sa.String(length=255), nullable=True),
    sa.Column('front_camera', sa.String(length=128), nullable=True),
    sa.Column('battery', sa.String(length=128), nullable=True),
    sa.Column('charging_wired', sa.String(length=255), nullable=True),
    sa.Column('charging_wireless', sa.String(length=255), nullable=True),
    sa.Column('network', sa.String(length=64), nullable=True),
    sa.Column('wifi', sa.String(length=64), nullable=True),
    sa.Column('bluetooth', sa.String(length=64), nullable=True),
    sa.Column('nfc', sa.String(length=64), nullable=True),
    sa.Column('dual_sim', sa.String(length=255), nullable=True),
    sa.Column('weight', sa.String(length=32), nullable=True),
    sa.Column('dimensions', sa.String(length=64), nullable=True),
    sa.Column('waterproof', sa.String(length=32), nullable=True),
    sa.Column('operating_system', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('variant_id')
    )
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('after_sales_cases',
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('case_type', sa.String(length=32), nullable=True),
    sa.Column('sub_type', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolve_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('compensation_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('handler', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index(op.f('ix_after_sales_cases_order_id'), 'after_sales_cases', ['order_id'], unique=False)
    op.create_index(op.f('ix_after_sales_cases_status'), 'after_sales_cases', ['status'], unique=False)
    op.create_index(op.f('ix_after_sales_cases_user_id'), 'after_sales_cases', ['user_id'], unique=False)
    op.create_table('inventory',
    sa.Column('inventory_id', sa.String(length=64), nullable=False),
    sa.Column('variant_id', sa.String(length=64), nullable=False),
    sa.Column('warehouse', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('available_qty', sa.Integer(), nullable=False),
    sa.Column('reserved_qty', sa.Integer(), nullable=False),
    sa.Column('safety_stock', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.variant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('inventory_id')
    )
    op.create_index(op.f('ix_inventory_variant_id'), 'inventory', ['variant_id'], unique=False)
    op.create_table('logistics_packages',
    sa.Column('logistics_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('package_id', sa.String(length=128), nullable=True),
    sa.Column('package_count', sa.Integer(), nullable=True),
    sa.Column('is_split_shipment', sa.String(length=8), nullable=True),
    sa.Column('carrier', sa.String(length=64), nullable=True),
    sa.Column('tracking_number', sa.String(length=64), nullable=True),
    sa.Column('current_status', sa.String(length=64), nullable=True),
    sa.Column('current_location', sa.String(length=128), nullable=True),
    sa.Column('estimated_delivery', sa.String(length=16), nullable=True),
    sa.Column('ship_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sign_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('logistics_id')
    )
    op.create_index(op.f('ix_logistics_packages_order_id'), 'logistics_packages', ['order_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('variant_id', sa.String(length=64), nullable=True),
    sa.Column('product_name', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.variant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('variant_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('official_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('price_type', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('effective_date', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.variant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id', name='uq_prices_variant_id')
    )
    op.create_index(op.f('ix_prices_product_id'), 'prices', ['product_id'], unique=False)
    op.create_index(op.f('ix_prices_variant_id'), 'prices', ['variant_id'], unique=False)
    op.create_table('store_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('variant_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('listing_status', sa.String(length=32), nullable=True),
    sa.Column('original_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('promotion_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_type', sa.String(length=32), nullable=True),
    sa.Column('promotion_id', sa.String(length=64), nullable=True),
    sa.Column('price_effective_from', sa.String(length=16), nullable=True),
    sa.Column('price_effective_to', sa.String(length=16), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('margin_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('on_shelf_date', sa.String(length=16), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.variant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku', name='uq_store_products_sku')
    )
    op.create_index(op.f('ix_store_products_product_id'), 'store_products', ['product_id'], unique=False)
    op.create_index(op.f('ix_store_products_variant_id'), 'store_products', ['variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """逆序删除应用结构，并保留可复用的 vector 扩展。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_products_variant_id'), table_name='store_products')
    op.drop_index(op.f('ix_store_products_product_id'), table_name='store_products')
    op.drop_table('store_products')
    op.drop_index(op.f('ix_prices_variant_id'), table_name='prices')
    op.drop_index(op.f('ix_prices_product_id'), table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_logistics_packages_order_id'), table_name='logistics_packages')
    op.drop_table('logistics_packages')
    op.drop_index(op.f('ix_inventory_variant_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_after_sales_cases_user_id'), table_name='after_sales_cases')
    op.drop_index(op.f('ix_after_sales_cases_status'), table_name='after_sales_cases')
    op.drop_index(op.f('ix_after_sales_cases_order_id'), table_name='after_sales_cases')
    op.drop_table('after_sales_cases')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_status'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_knowledge_chunks_embedding_hnsw', table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('sync_manifests')
    op.drop_index(op.f('ix_sources_product_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_table('roles')
    op.drop_table('promotions')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_logistics_events_logistics_id'), table_name='logistics_events')
    op.drop_table('logistics_events')
    op.drop_index(op.f('ix_knowledge_documents_category'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_table('intent_taxonomy')
    op.drop_index(op.f('ix_evaluation_dataset_category'), table_name='evaluation_dataset')
    op.drop_table('evaluation_dataset')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_conversation_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_agent_traces_user_id'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_trace_id'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_conversation_id'), table_name='agent_traces')
    op.drop_table('agent_traces')
    # ### end Alembic commands ###
