"""initial schema

Revision ID: 8fcb26067dd1
Revises: 
Create Date: 2026-09-04 04:42:14.842831

"""
from alembic import op
import sqlalchemy as sa


revision = '8fcb26067dd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """升级到初始版本；现有数据库结构由初始化脚本创建，因此无需额外 DDL。"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """从初始版本降级；该基线迁移不自动删除业务表。"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
